### ISSUE TITLE
Move giving.cu.edu/essentialcu HTML/CSS/JS and remove redirect.

### ISSUE THREAD

**Issue by kreynen** [CUCentralAdvancement/essential-cu#102]
this is related to https://github.com/CUCentralAdvancement/essential-cu/issues/85 and https://github.com/CUCentralAdvancement/essential-cu/issues/83

That HTML was created by E3 as a stand alone page. There were some Views created to dynamically link the Drupal nodes, but that was never used.

With https://github.com/CUCentralAdvancement/essential-cu/issues/76, I wasn't able to find a way to have the index.html resolve at the directory root. Going to continue looking at that.

**Comment by kreynen** [comment]
@alexfinnarn @mattroush I think this is good enough since it's the same HTML/CSS/JS and no worse than what's on giving.cu.edu now. The header/footer options can obviously be improved, but I can't see any issues in how next.js is routing this or how Fastly is caching it. 

Even without Fastly, https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgiving.cu.edu%2Fessentialcu%2F scores the Pantheon site a 22 and the review app without Fastly https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fessential-cu-feature-10-guqo2x.herokuapp.com%2Findex.html a 34.

**Comment by mattroush** [comment]
@kreynen I think it looks great, and definitely feels faster.

**Comment by kreynen** [comment]
@alexfinnarn any issue with merging this in now and adding the wildcard redirects on the giving.cu.edu side? It won't generate a lot of traffic, but would be more than 0 traffic through the prod instance and Fastly config.

**Comment by mattroush** [comment]
Let's have @tskillern review it on review app before we merge. Tim -- this is to move essential cu microsite from giving.cu.edu to this new essential.cu.edu site. You can see it and give it whirl here: https://essential-cu-feature-10-guqo2x.herokuapp.com/index.html

@kreynen @alexfinnarn

**Comment by alexfinnarn** [comment]
Seems like a lot of files for one page, but...if it works, who cares at this point? I wouldn't think the scss files are needed if the CSS is already compiled, but whatevs.

**Comment by tskillern** [comment]
@mattroush looks good to me. Thanks. 

cc @kreynen @alexfinnarn

**Comment by kreynen** [comment]
Deployed without issue to staging, but first attempt at deploying to production failed with...

```
       Installing Cypress (version: 5.0.0)
       
       [13:48:25]  Downloading Cypress     [started]
       [13:48:26]  Downloading Cypress      0% 0s [title changed]
       [13:48:26]  Downloading Cypress      1% 10s [title changed]
       [13:48:26]  Downloading Cypress      3% 7s [title changed]
       [13:48:26]  Downloading Cypress      5% 6s [title changed]
       [13:48:26]  Downloading Cypress      8% 5s [title changed]
       [13:48:26]  Downloading Cypress      11% 4s [title changed]
       [13:48:26]  Downloading Cypress      14% 4s [title changed]
       [13:48:26]  Downloading Cypress      14% 4s [failed]
       [13:48:26] → The Cypress App could not be downloaded.
       
       Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration
       
       Otherwise, please check network connectivity and try again:
       
       ----------
       
       URL: https://download.cypress.io/desktop/5.0.0?platform=linux&arch=x64
       Error: read ECONNRESET
       
       ----------
       
       Platform: linux (Ubuntu - 18.04)
       Cypress Version: 5.0.0
       The Cypress App could not be downloaded.
```

Made no changes. Deployed again. Worked.
