### ISSUE TITLE
Minor clean-up fixes 

### ISSUE THREAD

**Issue by tskillern** [CUCentralAdvancement/essential-cu#109]
@duquennoisa 

Here's an issue for a running list of clean-up fixes that I'll ask Kelly to make once we're in that spot. If you have any to add, please do so soon in comments on this issue. Are you still wanting to change the background color and add that CSS attribute to the background image? If so, please add what you want that to look like.

@pspaeth -- Just heads-up that I'm compiling this running list of minor clean-up fixes to the site -- mostly text changes. I don't have them in a "final" place to share with Kelly yet since it's probably good to get all of them to him in one batch, rather than piecemeal. What do you think would be the best ETA (day and time) to get him a final list?

1. Financials: Remove "It adds up:" from intro on financials -- I think there are just too many decks/rows of text here. 

![remove it adds up](https://user-images.githubusercontent.com/70039323/95940474-a688b080-0d9b-11eb-8937-4ff7e84ee8f3.png)

2. Financials: Use this new text in the highlighted portion for "Investment return vs. policy benchmark": 

`In fiscal year 2020, the LTIP returned 4.2% compared to 3.8% for our policy benchmark. Here is the LTIP’s annualized investment performance compared to the benchmark.`

![new text for LTIP vs policy benchmark](https://user-images.githubusercontent.com/70039323/95939927-7260c000-0d9a-11eb-8b7c-0d05d84fb10f.png)

3. Financials: In the very last thing on the page (See our audited financials...), please make these updates:

-  Use this URL: https://essential.cu.edu/r/index.html?doc=onward2020-pdf
-  Link to the text as well as the button.
-  Change the button text to say "Download here" 

4. Home page: The line height in the intro paragraph is a bit tight. It should be the same as the financials paragraph that's down the page.

![leading should be like financials module graph](https://user-images.githubusercontent.com/70039323/95940524-ca4bf680-0d9b-11eb-8c26-bb142251eba6.png)
 
5. Global header: In mobile, can you center the header? 

![mobile header off center](https://user-images.githubusercontent.com/70039323/95940898-b8b71e80-0d9c-11eb-8f88-d683e698c8e8.png)

**Comment by duquennoisa** [comment]
Thanks for getting this started @tskillern !

Here are some additional edits I've noted:

1. Global background color and background image:

-change global background color to #F5F1E5
-change top and bottom background image` background-image: url(/bkgd-goldwash.jpg);`  blend-mode to multiply 
-change ` background-image: url(/bkgd-goldwash.jpg);` opacity to 75%

2. Addressing item 4 on Tim's list :

> Home page: The line height in the intro paragraph is a bit tight. It should be the same as the financials paragraph that's down the page. leading should be like financials module graph

-change that text from h2 to body-text

**Comment by kmackvolt** [comment]
@tskillern @duquennoisa 
I thought the financials content was finalized when I developed it, but I am seeing a discrepancy in what I developed vs what's shown in Invision. Which one is correct?

**Invision:**
<img width="464" alt="financials-content-invision" src="https://user-images.githubusercontent.com/40502718/96030096-6fa0b200-0e10-11eb-9500-05d053167ac8.PNG">

**As developed**
<img width="616" alt="financials-content-developed" src="https://user-images.githubusercontent.com/40502718/96030099-70394880-0e10-11eb-92fa-2270ad5eec66.PNG">

**Comment by tskillern** [comment]
@kmackvolt My apologies that our request for a fix got out of order. I meant to flag this last night when I sent you the financials images and didn't include in the issue I created.

Invision is correct. 

So please (1) remove the "92% of gifts were less than $2,500 each" from below the image. And (2) make the content fix as shown in Invision. 

Thanks, and sorry for the confusion.

**Comment by tskillern** [comment]
I edited a comment above to include this URL as the last link in the financials page. Putting here too for visibility: 

https://essential.cu.edu/r/index.html?doc=onward2020-pdf
