### ISSUE TITLE
Story image caption and alt text

### ISSUE THREAD

**Issue by tskillern** [CUCentralAdvancement/essential-cu#113]
As mentioned during review of https://github.com/CUCentralAdvancement/essential-cu/pull/106

> Re: duplicate the ALT text as a caption, and insert that into the story body text for rendering.

**We need to display the caption data (not alt tags) on the page for the caption area since they are likely to be substantially different.** I understand the captions in most instances (or all) had no values. I have since asked Melanie to insert captions through the CMS, which she did not know she needed to do. I have one example below if helpful. 

Is this approach possible? >> If `data-caption` has a value, display it. If `data-caption` doesn't have a value, display nothing. (If not possible, and all photos need to have captions, we will write them -- but hoping this might be easier.)

If helpful for you @kmackvolt I have added a photo to the top of this story that has caption and alt text contained in the image tag: https://essential-stage.cu.edu/impact-reports/onward/boulder-symphony

![alt-text-and-caption](https://user-images.githubusercontent.com/70039323/96052078-06ce2f80-0e3a-11eb-9f84-fd88773123d2.jpg)

**Comment by tskillern** [comment]
@pspaeth for cc

**Comment by kmackvolt** [comment]
Will do.
I didn't know there was a data-caption value on the images, as the stories I tested didn't have them.
If the value doesn't exist, no caption will show.

**Comment by tskillern** [comment]
Thanks. Our fault – we didn’t provide any through the data.

**Comment by kmackvolt** [comment]
This particular story also shows a problem in how I handled parsing the images to rewrite the HTML to allow for the out of container structure and caption. I was looking for IMG tags within P tags, again because that's what the stories I tested showed; this example story shows an IMG tag NOT contained in a P tag, so I need to account for that as well.

**Comment by tskillern** [comment]
Thanks for catching that @kmackvolt and finding a fix. 

I was going to flag that for @alexfinnarn on our side actually. Alex, this is possibly a moot point now that Kelly has fixed IMG tags that are not contained in P tag.
