### ISSUE TITLE
Flip text/chart on financials

### ISSUE THREAD

**Issue by tskillern** [CUCentralAdvancement/essential-cu#118]
@kmackvolt @pspaeth 

I have pored over the site. This is the only fix I can identify. Thanks guys. It looks great. 

1. Please swap the order of these two elements on mobile: 

![reorder waffle chart](https://user-images.githubusercontent.com/70039323/96311068-e632e080-0fc5-11eb-9257-a04f4e097c88.png)

**Comment by kmackvolt** [comment]
PR for that:
https://github.com/CUCentralAdvancement/essential-cu/pull/119
