### ISSUE TITLE
Class based click tracking is not firing in GTM

### ISSUE THREAD

**Issue by kreynen** [CUCentralAdvancement/essential-cu#121]
For some reason the story card links are not firing when a class of `storycard-link` is used to limit the trigger. 

<img width="998" alt="Screen Shot 2020-10-21 at 9 34 55 AM" src="https://user-images.githubusercontent.com/385234/96743035-cc581b80-1380-11eb-9970-34816ce4de9d.png">

<img width="1437" alt="University_of_Colorado_2020_Donor_Impact_Report" src="https://user-images.githubusercontent.com/385234/96743610-6d46d680-1381-11eb-9092-806d5a143894.png">

Not sure what can be targeted here since stories don't have a url patter. May just use a URL exception since the only other pages in the project are the homepage and financials.

**Comment by mattroush** [comment]
@alexfinnarn - I'm not sure if he resolved this or not, as it sounds like a tag manager thing more than a code thing. regardless, not a priority.
