### ISSUE TITLE
Content Updates

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/essential-cu#128]
@mattroush @tskillern Do you want me to make these changes?

---

### HOME PAGE
https://essential.cu.edu/impact-reports/onward

**1. Under CU philanthropy:**

Change dash to a colon: “Your generosity creates impact: bright futures for...”

![Screen Shot 2020-11-02 at 12 51 12 PM](https://user-images.githubusercontent.com/70039323/97912504-24403c00-1d0a-11eb-94f2-59b63fcdfd61.png)

**2. Under Our Mission:** 

The word "donor" should be "donors"

![Screen Shot 2020-11-02 at 12 16 51 PM](https://user-images.githubusercontent.com/70039323/97909360-5602d400-1d05-11eb-82bf-320a557ba180.png)

### FINANCIALS page
https://essential.cu.edu/impact-reports/onward/financials

**1. In the intro:**

Add a space on each side of both dashes.

![Screen Shot 2020-11-02 at 12 52 41 PM](https://user-images.githubusercontent.com/70039323/97912810-8dc04a80-1d0a-11eb-9d1c-57b6bcb61d23.png)

**2. In the 55,450 gifts paragraph:**

Change the dash to a colon.

![Screen Shot 2020-11-02 at 12 52 48 PM](https://user-images.githubusercontent.com/70039323/97912805-8d27b400-1d0a-11eb-8047-d3e939a8a31f.png)

**3. Under the COVID/DEI section:**

a. Change both instances of "COVID" to "COVID-19"

b. Change "since March 1" to "from March 1 to June 30"

c. Change "since January 1" to "from January 1 to June 30"

![Screen Shot 2020-11-02 at 12 21 05 PM](https://user-images.githubusercontent.com/70039323/97909969-4768ec80-1d06-11eb-94fe-d72d02c27db6.png)

**4. In the You’re looking ahead paragraph:**

Replace the dash with a space.

![Screen Shot 2020-11-02 at 12 53 02 PM](https://user-images.githubusercontent.com/70039323/97912812-8ef17780-1d0a-11eb-9170-13f1d44477c7.png)

**4. In $1.52 billion paragraph:**

Change $73 million to $75 million:

![Screen Shot 2020-11-02 at 2 27 44 PM](https://user-images.githubusercontent.com/70039323/97922156-442b2c00-1d19-11eb-9ee9-b7a3f802b246.png)

**Alt text on financials page**

Also on the financials page, I think we should change the existing alt text for the graphs/charts that appear in the second half. One thing I didn’t anticipate was that because the graphs/charts are images, there is no literal text, so a page reader would not translate what’s in the image. Thus, we need to include the actual numbers. Here are the replacement alt text values for each: 

1. $1.52 billion chart alt text: 

“This is a bar chart that shows the value of the CU endowment by year. Here are the values: $1.09 billion for 2015, $1.06 billion for 2016, $1.22 billion for 2017, $1.36 billion for 2018, $1.45 billion for 2019 and $1.52 billion for 2020.”

2. How the endowment is invested alt text: 

“This is a chart that shows how the LTIP is invested in asset classes. 46.3% for global public equities, $24.7% for global private capital, 13.1% for global hedge funds, 8.7% for real assets and 7.2% for fixed income and cash.”

3. Investment return vs. policy benchmark alt text: 

“This is a dual bar chat that compares the LTIP and benchmark returns. Here are the percentage returns: 3 year for LTIP is 7.2%, 3 year for benchmark is 6.2%; 5 year for LTIP is 7.9%, 5 year for benchmark is 7.5%; 10 year for LTIP is 8.4%, 10 year for benchmark is 8.9%; 15 year for LTIP is 7.4%, 15 year for benchmark is 6.1%.”:

4. $209 million alt text: 

“This is a waffle chart that shows where support from the CU Foundation to CU goes, by percentage. Academic Support 36%; Capital Projects 12%; Research 12%; Scholarships 12%; Advancement support 12%; Chairs, Professorships and Other Faculty Support 10%; Public Service, Administration, Library and Other Support 5%; and Athletics 1%”

**Comment by tskillern** [comment]
@alexfinnarn yes, pls make these changes. Thanks.
