### ISSUE TITLE
Overwrite PDF that's linked from financials page

### ISSUE THREAD

**Issue by tskillern** [CUCentralAdvancement/essential-cu#131]
@alexfinnarn 

We need to overwrite the PDF at this link: 

https://essential.cu.edu/files/cuf-audited-financial-statements-fy-2020.pdf

This new PDF is here: 

[cuf-audited-financial-statements-fy-2020.pdf](https://github.com/CUCentralAdvancement/essential-cu/files/5495678/cuf-audited-financial-statements-fy-2020.pdf)

The only information I have about this is what Kevin put in this Slack message: 

https://advancementcentral.slack.com/archives/C011B0N7TB4/p1602681840029300?thread_ts=1601924466.123800&cid=C011B0N7TB4

**Comment by alexfinnarn** [comment]
@tskillern I had to push to production for you to test so it closed the issue...but the PDF link on https://essential.cu.edu/impact-reports/onward/financials should be updated. PDF shows up for me but I didn't test the marketing/email path/redirect or whatever that user journey is supposed to be.

**Comment by tskillern** [comment]
@Alex Finnarn<mailto:notifications@github.com> it’s going through the “front door” so looks like it’s working. Thank you.
