### ISSUE TITLE
Update promo block on about us pages

### ISSUE THREAD

**Issue by mattroush** [CUCentralAdvancement/essential-cu#136]
- Update image [in this](https://giving.cu.edu/admin/structure/block/manage/block/6/configure) block to [this image](https://www.dropbox.com/s/e2j6yt4sr5fhn2p/IR20-Medallions-nocampus.png?dl=0).
- Link button and image to https://essential.cu.edu/impact-reports/onward

**Comment by alexfinnarn** [comment]
@mattroush updated on https://giving-test.cu.edu/about-us/university-colorado-foundation but the alt text for the image is old. What should that say?

**Comment by tskillern** [comment]
Alt text: "2020 Impact Report"

Per @mattroush can the image be clickable? URL for that image and the link below should be https://essential.cu.edu/impact-reports/onward/?utm_campaign=2020ImpactReport&utm_source=GivingWeb so that we can track.

**Comment by alexfinnarn** [comment]
@tskillern block updated with changes at updated on https://giving-test.cu.edu/about-us/university-colorado-foundation

**Comment by mattroush** [comment]
@alexfinnarn these look good to me. @tskillern?

**Comment by tskillern** [comment]
Yes, this is good. @mattroush @alexfinnarn
