### ISSUE TITLE
Retain utm params in URL on r/index.html redirect

### ISSUE THREAD

**Issue by mattroush** [CUCentralAdvancement/essential-cu#137]
Google Analytics is not capturing campaign, source, etc for most visits that go through /r/index.html redirect. I have a feeling that redirect is happening too fast for google tag manager to load analytics script and capture utm campaign params, which then means we lose the ability to tie session traffic to google campaign for remainder of that user’s session.

This should show at least 4 sessions, but only shows one:
![Screen Shot 2020-11-10 at 8 58 22 AM](https://user-images.githubusercontent.com/64887812/98698493-50c00d80-2333-11eb-83a5-d4ca3c6a5dfe.png)

Only solution I can think of is to modify code that’s stripping query parameters so that params starting with `utm_` are retained in redirect to /impact-reports/onward. We don't want to keep the other params (e.g. `sfmc_sub`, `j`, etc), but do want to keep the utm params. My thought is that they would be captured and sent to google analytics when user lands on home page instead.

Could you take a look at [/r/index.html](https://github.com/CUCentralAdvancement/essential-cu/blob/master/public/r/index.html) and see if you're able to make that modification?

**Comment by alexfinnarn** [comment]
@mattroush But what about subsequent clicks? The query params wouldn't be retained for those links.

Also, why not just send the email to "/impact-reports/onward" with the query params then? Isn't the only thing the "/r/index.html" does is add the cookies?

**Comment by mattroush** [comment]
@alexfinnarn utm params only need to be captured once per session, google then tags that session and tracks all traffic for that session under that campaign, source, medium, etc.

We still need /r/index.html though. The primary reason for it is to parse out param values and create cookies necessary for dynamic content on homepage and for marketing cloud tracking to work. see #76 and #64  The whole google analytics piece of that was just something extra Kevin through in so he could just wipe all params instead of keeping some, but it's not working.

**Comment by alexfinnarn** [comment]
@mattroush  https://essential-cu-feature-13-hiquzt.herokuapp.com/r/index.html?foo=bar should keep the query param, but I don't know anything more to check.

**Comment by mattroush** [comment]
@alexfinnarn the params are being retained, which is good. is there any way to still strip some parameters? the only ones we really need to retain are the ones that start with `utm_`... Not the end of the world if not, but would be preferred as the others contain things like user's email address which we'd like to take out of URL if possible.

**Comment by alexfinnarn** [comment]
of course, there is a way to do that...plus bunches of other improvements. 

If the only concern is that the URL ends up being slightly longer, I don't think it's worth the time to do. Any code change can introduce bugs and people are already using it.

**Comment by mattroush** [comment]
The concern is that a person's email appears in the address bar, so a minor privacy concern - especially if someone forwards the email out or copies and shares the marketing cloud link directly in the email and then it gets shared beyond their social sphere and then makes it to someone who otherwise wouldn't have that person's email address. if they click the link in the email, they'll eventually get to a url that has the original recipient's email in it.

**Comment by alexfinnarn** [comment]
I don't consider that a privacy concern, but taking it out of the second redirect doesn't mitigate that anyway. It still shows up in the link they click, just not what they eventually land on. If no query params are passed, it's still in the link...you turn JS off, you have an email address + any other query param.

**Comment by mattroush** [comment]
ok, well we'll leave as is - go ahead and push up and we'll see if analytics are now capturing properly. Thanks!

**Comment by alexfinnarn** [comment]
@mattroush pushed to production and keeps the query params for me.
