### ISSUE TITLE
Add Marketing Cloud Tracking

### ISSUE THREAD

**Issue by kreynen** [CUCentralAdvancement/essential-cu#26]
We need to be sure to use `Set-Cookie: name=value; domain=cu.edu` or the giving.cu.edu site won’t be able to read the cookies set on essential.cu.edu

**Comment by alexfinnarn** [comment]
Probably best done with Express middleware in https://github.com/CUCentralAdvancement/essential-cu/blob/master/server.js. 

There is a simple way to use the cookies object on request/response: https://alligator.io/nodejs/express-cookies/ ...also lists other useful middlewares.

Or https://github.com/expressjs/cookie-session looks to be more official and has notes about load balancing scenarios which could definitely be an issue with Heroku. Since this is a server-side dependency, it shouldn't affect page weight and might be harmless to add.

**Comment by kreynen** [comment]
Testing this in https://github.com/CUCentralAdvancement/cu-giving/issues/36 now

**Comment by kreynen** [comment]
The hope was to be able to reuse utm values as cookies with the frontdoor approach and avoid needing marketing code beyond https://github.com/CUCentralAdvancement/essential-cu/issues/25 in the front end projects. The challenge I'm running into is that while GTM can be used to add javascript "on top of" the project, the Marketing Cloud data extension update requires a token. In D7, I was generating the token every hour via cron with a client id and secret only the server knew in https://github.com/CUCentralAdvancement/cu-giving/blob/master/sites/all/modules/custom/cu_fund_blocks/cu_fund_blocks.module#L478

That token is then available to the block or checkout to push data to update the data extension. Trying to do all of that in a GTM tag with just javascript, I'm running into a CORS error...

```
Access to XMLHttpRequest at 'https://mc3d7mrzbxcc-1byr17kn3kyfzp4.auth.marketingcloudapis.com/v1/requestToken' from origin 'https://essential.cu.edu' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

It looks like there is a way to add the requesting domains in Salesforce https://help.salesforce.com/articleView?id=extend_code_cors.htm&type=5. Not sure if that is an option.

Researching alternatives now.

**Comment by alexfinnarn** [comment]
You can use API routes via Next.js to generate the token and pass data back and forth https://github.com/CUCentralAdvancement/essential-cu/blob/master/pages/api/hello.js

That's what I did for authorize.net code to get around CORS. https://github.com/CUCentralAdvancement/giving-frontend/blob/master/pages/api/authorize-token.js

**Comment by kreynen** [comment]
Another problem is that generating tokens invalidates the previous token... at least in the v1, non-oauth tokens. In D7, my goal was to generate and keep an active token at the service level. Even between my local, dev, test and prod we were running into token issues. Currently all of these implementation are using the same client id/secret combination to update the same data extension. 

What I'm really looking for is the MC API version of https://help.salesforce.com/articleView?id=extend_code_cors.htm&type=5 where the requesting site domain can be added to an allowlist. There are other API calls that require adding the domain to an allowlist in Authorize. I'd be surprised if there wasn't a way to configure CORS in Authorize as well.

If we can get this to work from within GTM, we can use the same approach on dynamic or static sites.

There will be exceptions to that like a checkout process where the confirmation page may not have access to all of the values we want to push to Marketing Cloud or the Enhanced eCommerce Google Analytics.

**Comment by kreynen** [comment]
A straight client side js isn't going to work. Even if I solve the problem of issuing a token without exposing the client id/secret by sharing the active D7 token, the attempt to POST to https://mc3d7mrzbxcc-1byr17kn3kyfzp4.rest.marketingcloudapis.com/data/v1/async/dataextensions/key:44F05A85-E234-439D-AF75-AEAB4BF97FE1/rows also has a CORS error as well. 

Adding JQuery (even from a CDN) to handle these posts as suggested in https://developer.salesforce.com/blogs/developer-relations/2015/08/creating-jquery-application-using-rest-api.html seemed heavy handed, but when I got to step 5 I realized that this was once again referring to Salesforce API where there is a CORS configuration. I still cannot find a CORS allow list option for the Marketing Cloud APIs.

**Comment by kreynen** [comment]
After talking to a few people with more Marketing Cloud experience and Matt, I switched directions to https://github.com/CUCentralAdvancement/cu-giving/issues/52. We still need some javascript added to GTM, but it will only be making a callback to giving.cu.edu.

**Comment by mattroush** [comment]
@alexfinnarn - we'll be testing and validating that this is working in the coming days, but prior tests have worked and so assume this can be closed after that unless something has broken.
