### ISSUE TITLE
Get A Handle On Analytics Integration

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/essential-cu#295]
Last year, there was a decent amount of time put into audience list building and tracking conversions via MC and GTM. This year, the process is more difficult since literally everyone that worked on analytics last year is gone this year...four people in total.

**Acceptance Criteria**

- [x] Look at Google Tag Manager triggers - https://tagmanager.google.com/#/container/accounts/147131779/containers/32252164/workspaces/11/triggers
- [x] Follow user from email entry to conversion
- [x] Decide on whether to update Data Extensions. Will lose the ability to track "people who opened last year's email" if not done.
- [ ] Use this issue for a test of the MC APIs - https://developer.salesforce.com/docs/marketing/marketing-cloud/guide/adding_data_to_data_extension_object.html

**Next Issue**

Follow up issues should be created (possibly from the checklist items) where code gets added as well as for testing purposes.

**Comment by kreynen** [comment]
@alexfinnarn and @imkleats, you might want to take a look at what I did with https://www.drupal.org/project/gtm_exclude_cookie for the Office of Digital Education (ODE). Similar situation where there isn't much traffic to the site/project and most of the traffic is directed there. ODE gets a little more organic traffic than the IR projects have gotten in the past, but both groups share the problem that with so little traffic, a few employees clicking around can really throw off the reporting.

You likely wouldn't need to jump through any of the hoops required to get Symfony to generated a HTTPOnly = false cookie (required for GTM to "see" the cookie) that isn't stripped by Pantheon, but you can still leverage the approach and using the reverse logic/regex to prevent the GTM triggers from firing. 

For ODE, staff remain all opted out of all analytics and retargeting unless they are specifically testing GTM. 

Let me know if you have any questions about how we combined level of engagement with a AR/IR in the past in the donation process.
