### ISSUE TITLE
Nav bar drop shadow

### ISSUE THREAD

**Issue by Feissit** [CUCentralAdvancement/essential-cu#345]
Medium Priority

Please add a drop shadow to the nav bar, on both the upper and lower sections

Top layer, white:

.rectangle {
  height: 98px;
  width: 1440px;
  border-radius: 0 0 30px 30px;
  background-color: #FFFFFF;
  box-shadow: 0 3px 4px 0 rgba(0,0,0,0.5);
}

Bottom layer, gold: 

.background-copy-atoms-colors-g {
  height: 70px;
  width: 1440px;
  box-shadow: 0 2px 4px 0 rgba(0,0,0,0.5);
}

<img width="1505" alt="Screen Shot 2021-10-13 at 2 14 58 PM" src="https://user-images.githubusercontent.com/91230278/137206218-9df2ec1b-d9eb-4f7f-aea1-0f8ae855bee9.png">

**Comment by duquennoisa** [comment]
this is fixed with #469
