### ISSUE TITLE
All buttons have a drop shadow

### ISSUE THREAD

**Issue by Feissit** [CUCentralAdvancement/essential-cu#346]
Medium priority

<img width="535" alt="Screen Shot 2021-10-13 at 2 19 21 PM" src="https://user-images.githubusercontent.com/91230278/137206756-463821f8-fd26-493b-89ad-260d642f3dd9.png">

These buttons are 38px high with a drop shadow as below

.button-copy-7-molecules-button {
  height: 38px;
  width: 111.47px;
  box-shadow: 0 2px 4px 0 rgba(0,0,0,0.5);
}

<img width="230" alt="Screen Shot 2021-10-13 at 2 19 44 PM" src="https://user-images.githubusercontent.com/91230278/137206810-570a37c4-f031-4b8c-bf4d-e9ffa6c54622.png">

Give now button is 45px high:

.shape-atoms-buttons-resources- {
  height: 45px;
  width: 132px;
  box-shadow: 0 2px 4px 0 rgba(0,0,0,0.5);
}

**Comment by duquennoisa** [comment]
Use tailwind shadow-md setting not sketch values. It will probably be good enough.

**Comment by duquennoisa** [comment]
fixed
