### ISSUE TITLE
Upload SVGs of social media icons

### ISSUE THREAD

**Issue by Feissit** [CUCentralAdvancement/essential-cu#353]

**Comment by Feissit** [comment]
Upload SVGs of share icons: twitter, fb, insta
Upload SVGs of Appreciate icons: thumbs up, heart, smiley

You've been putting them here:

https://www.dropbox.com/home/ADVMarComm%20Team%20Folder/01-CURRENT%20PROJECTS/2021/IR21/Web-Elements/Global

**Comment by alexfinnarn** [comment]
@duquennoisa I think this issue should be closed now?

**Comment by duquennoisa** [comment]
yep
