### ISSUE TITLE
Upload four impact stories to CMS

### ISSUE THREAD

**Issue by Feissit** [CUCentralAdvancement/essential-cu#362]
Here are the four stories for the CMS. Photos are included, let me know if you need any files or have any questions, and **please ping me when they are up**.

[Story 1: Anschutz](https://www.dropbox.com/scl/fi/m1vsy7ugt8sz9aq2mi5yn/Gyn-Onc_Carolyn-Lefkowits_Ready-for-Tim-FInal-Review.docx?dl=0&rlkey=norkhxc6f1dxxfrqw31rud0ft)
[Story 2: Boulder](https://www.dropbox.com/scl/fi/silho2omsu925gr71xro3/Stephanie-Saltis_Ready-for-Tim-Review.docx?dl=0&rlkey=kp350ourrpvkz99rry2ujo843)
[Story 3: Denver](https://www.dropbox.com/scl/fi/7df9l7dokvyy054vizjxi/Graham_Aleaza_Ready-for-Tim-Final-Check.docx?dl=0&rlkey=p18h0znlxv20rpjr4ub2l16jc)
[Story 4: UCCS](https://www.dropbox.com/scl/fi/uddzj05304nfcpr859vhz/JG_Ready-for-Tim-Final-Review.docx?dl=0&rlkey=acpesn5yem2mqg8o7nmsjra24)

**Comment by alexfinnarn** [comment]
@Feissit I uploaded the four stories in the production instance of the CMS and they can be seen on https://essential-staging-cu.herokuapp.com/impact-reports/joy. I used the images in the story as placeholders.

Of course, there are still styling differences between the mock and the story page/cards output, but I noticed two content-related items while uploading stories.

1. The block quotes have quotes within them which makes it look weird surrounding the quoted content with larger quote marks. When I see block quotes in articles I think the attribution is assumed...or put after the quote with a hyphen `- John Does`.
2. Some images are longer than others making the aspect ratio inconsistent throughout the story. Images can be automatically cropped or manually done, but I think in general, the image should have widths greater than heights.

I can make issues out of those two things after gathering feedback.
