### ISSUE TITLE
Create Financials Snippet for story pages

### ISSUE THREAD

**Issue by duquennoisa** [CUCentralAdvancement/essential-cu#366]
Each story has a segment that relates financial information or gift mechanisms to the story and that links to the financials page. This aims to connect deepen the story and financial content. The "segment" has a design that creates a distinction or break in the story narrative in the "did you know" box mannerism. 

Desktop: 
![image](https://user-images.githubusercontent.com/70037329/137704567-32b30055-7c39-4b48-bb65-5a4f8b120050.png)

Mobile:
![image](https://user-images.githubusercontent.com/70037329/137704635-b3f96796-38b2-4990-bd06-42e7a9b4080d.png)

**Acceptance Criteria**

- [x] Ensure that each financial segment has a title (8 words or less). 
- [ ]  A distinct segment with design as provided in the story page mock up. 
- [ ] Active link to the financial page
- [ ] Image title  paragraph and link elements. 

**Next Issue**

This code can be deployed.

**Comment by alexfinnarn** [comment]
@duquennoisa Is this ready to be implemented? 

It involves updating code in the CMS so best to do before handing over the CMS and calling that side of things "done". https://github.com/CUCentralAdvancement/essential-cu/issues/383 is also a code change. I'm trying to group the remaining CMS changes together.

**Comment by duquennoisa** [comment]
@alexfinnarn Yes this is ready to be implemented. The #383  issue is a copy change that I assume is coming from Tim so I think we can call that done also-- theres still a small chance that it could change but I doubt it.
