### ISSUE TITLE
IR21 eComm needs

### ISSUE THREAD

**Issue by ktheiler** [CUCentralAdvancement/essential-cu#375]
Coordinating needs around email lists, e-newsletter dissemination and social media posts to share IR21. All elements of eComm around IR21 will need to work in tandem with analytics reporting.

- [x] Gather EIDs for email lists
- [x] Coordinate graphic, blurb and link for e-newsletters on each campus
- [x] Coordinate graphic, blurb and link for social media posts on each campus

**Comment by Feissit** [comment]
@ktheiler All links generated and entered [here](**https://teams.microsoft.com/_#/xlsx/viewer/teams/https:~2F~2Fcu0.sharepoint.com~2Fteams~2FIR21~2FShared%20Documents~2FGeneral~2FeComm~2FIR21%20Campaign%20Tracking.xlsx?threadId=19:gwzVOfsGLiYVt7P6urEubBo-J-m541hZW1k0bDB8wQc1@thread.tacv2&baseUrl=https:~2F~2Fcu0.sharepoint.com~2Fteams~2FIR21&fileId=3cad6449-c38b-4800-82eb-9a5f86482897&ctx=files&rootContext=items_view&viewerAction=view**)
