### ISSUE TITLE
Change Base Font To Roboto Light and Font Size

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/essential-cu#393]
```html
 <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,400&display=swap" rel="stylesheet"></link>
```

@duquennoisa I'm using the same thing Kelly used last year. It looks like Roboto was used with italics and those font weights. I believe 400 is the default now, but I bet you want 300? `font-weight: 300` is what was used last year. 

We can use the semantic class names Tailwind has https://tailwindcss.com/docs/font-weight where so far I've only used `font-bold` for headers and other bolded text.

Feel free to update or edit the acceptance criteria.

**Acceptance Criteria**

- [x] Change URL to download requested font family and weights.
- [x] Update defaults for font-weight to 300.
- [x] Keep bold font-weight at 700
- [ ] Set base-level font-size and line-height on body

**Comment by duquennoisa** [comment]
This looks done to me
