### ISSUE TITLE
Force app to use https

### ISSUE THREAD

**Issue by kreynen** [CUCentralAdvancement/essential-cu#43]
As a general policy for both security and SEO, we want everything running on cu.edu to use https over http. Heroku supports both the http and https protocols for apps by default. Because of the way SSL is terminated at the load balancer and traffic between the load balancer and the dynos within Heroku's internal network is not encrypted in the common runntime, getting an app to default into https can be tricky. https://www.npmjs.com/package/force-ssl-heroku claims to handle this for apps using Express.

There may be a better way to do this, but force-ssl-heroku is a way.

**Comment by alexfinnarn** [comment]
Heroku seems to redirect by default as http://essential-cu.herokuapp.com/impact-reports/onward always ends up on HTTPS for me. If redirecting the initial request is fine then I think this is already covered. To my understanding, the NPM package mentioned above performs a redirect on specified paths so it looks like similar behavior without the need to add a dependency.

**Comment by kreynen** [comment]
http://essential-stage.cu.edu/ -> http://essential-stage.cu.edu/impact-reports/onward
Going directly to a url like http://essential-stage.cu.edu/impact-reports/onward/druwrasewagituthesleshistosluvanofriladrovushuwrusliuanaspauaphathibrivewrowrude does not redirect

**Comment by alexfinnarn** [comment]
I would try to just use the conditinal in https://github.com/rangle/force-ssl-heroku/blob/master/force-ssl-heroku.js into the `server.js` file in this project.

```js
  if (process.env.NODE_ENV === 'production' &&
    req.headers['x-forwarded-proto'] !== 'https') {

    sslUrl = ['https://', req.hostname, req.url].join('');
    return res.redirect(sslUrl);
  }
```

**Comment by kreynen** [comment]
Fastly is forcing the production instance into https, but this is not working as expected. Attempts to access http://essential.cu.edu/impact-reports/onward are redirected to https://essential-cu.herokuapp.com/impact-reports/onward. Going directly to https://essential.cu.edu/impact-reports/onward works as expected with a valid cert.

<img width="858" alt="Screen Shot 2020-10-07 at 2 38 35 PM" src="https://user-images.githubusercontent.com/385234/95385159-d66f1a00-08aa-11eb-8125-abc23afec41c.png">

**Comment by kreynen** [comment]
I tried overriding host header from essential-cu.herokuapp.com to essential.cu.edu in the configuration, that solves the issue in the redirect but results in a Heroku level error.

<img width="674" alt="Screen Shot 2020-10-07 at 2 42 25 PM" src="https://user-images.githubusercontent.com/385234/95385910-d7547b80-08ab-11eb-88fd-1c0f6954d2fb.png">

I turning off the `Force TLS and enable HSTS` option resulted in Fastly resulted in being able to access a URL like http://essential.cu.edu/impact-reports/onward  with a `Not Secure` warning. Going to look at the option @alexfinnarn suggested in https://github.com/CUCentralAdvancement/essential-cu/issues/43#issuecomment-702841789

**Comment by alexfinnarn** [comment]
keep in mind https://status.heroku.com/incidents/2110 is not resolved and showed up today.

**Comment by alexfinnarn** [comment]
```js
server.all("*", (req, res) => {
  if (req.port === 3000 || req.headers['x-forwarded-proto'] !== 'https') {
    console.log(req.protocol);
    const host = req.hostname == 'localhost' ?  'localhost:3443' : req.hostname;
    return res.redirect('https://' + host + req.originalUrl);
  }

  return handle(req, res);
});
```

I tried my hand at this and kept running into redirect loops. Heroku seems to turn HTTPS requests back into HTTP requests causing a loop. `console.log(req.protocol)` kept logging as "http" which seems impossible with `return res.redirect('https://' + host + req.originalUrl)` following. That's why I think headers need to be used based on spooky Heroku networking.

With a lot of other issues to work on, I don't think this issue is that important to fix, but it probably does relate to what's happening with Drupal on Heroku and HTTP/HTTPS redirect issues.

**Comment by alexfinnarn** [comment]
https://help.heroku.com/J2R1S4T8/can-heroku-force-an-application-to-use-ssl-tls

Heroku recommends using a different node package...well, they point to a search page and then a different package pops up. 

I made https://github.com/CUCentralAdvancement/essential-cu/pull/120 which might work but probably needs to be tested on staging and production as I think review apps are still `process.env.NODE_ENV === 'dev'`.

The review app gives a 503 but nothing in the logs so maybe this is related to Heroku intermittent failures with the build phase?

**Comment by alexfinnarn** [comment]
```js
// This should be done on the server, but Heroku's internal networking makes it difficult.
if (window.location.host === 'essential.cu.edu' && window.location.protocol !== 'https:') {
  window.location.href = 'https://' + window.location.host + window.location.pathname + window.location.search;
}
```

Not a great "solution" but it works and doesn't cause a redirect loop. Since Next.js uses a template to generate pages, it only has to be placed in one spot...I could actually run this at a higher level so it doesn't have to be in the actual template files, but I guess it's fine for this project. Next.js might only fire it for the initial page load too.

**Comment by alexfinnarn** [comment]
This was done "well enough" for the project.
