### ISSUE TITLE
Add padding between hero image and hero text in story pages

### ISSUE THREAD

**Issue by duquennoisa** [CUCentralAdvancement/essential-cu#449]
I noticed theres no padding between the two hero items: 
![image](https://user-images.githubusercontent.com/70037329/139211107-d967638d-8425-4112-89d3-ecf6718064f4.png)

I added 1 rem on top and 2rem on the right on the image and I think it looks good for lg+ screens. Thoughts? 
![image](https://user-images.githubusercontent.com/70037329/139213140-b3c4e038-e5f4-43d7-93d6-738857a2dc74.png)

**Acceptance Criteria**

- [ ] fixed padding on hero module for story pages

**Comment by alexfinnarn** [comment]
Padding removed.
