### ISSUE TITLE
Apply turquoise body text link styling from Homepage to links in the stories and financials cards.

### ISSUE THREAD

**Issue by Feissit** [CUCentralAdvancement/essential-cu#464]
Apply turquoise body text link styling from Financials to links in the stories and financials cards. These are external links, can you make them open in a new tab? If that's difficult at this point, then skip for now.

<img width="485" alt="Screen Shot 2021-10-29 at 11 29 21 AM" src="https://user-images.githubusercontent.com/91230278/139477790-68232241-a8cb-43e9-bf73-8c838ef6c175.png">

<img width="829" alt="Screen Shot 2021-10-29 at 11 30 08 AM" src="https://user-images.githubusercontent.com/91230278/139477903-78cd5f2e-a6df-4e4b-81e2-c9250d73503b.png">

**Comment by alexfinnarn** [comment]
The link color and bold are updated for links in stories, financial snippets, and the related fund's links. There's at least one other place where the link color isn't the same, but it follows the design. Let me know any other links that need changes.

**Comment by Feissit** [comment]
Looks good

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
