### ISSUE TITLE
Related fund links aren't working

### ISSUE THREAD

**Issue by Feissit** [CUCentralAdvancement/essential-cu#466]
When I click on any of the related fund links, the URL populates like this: https://giving.cu.eduhttps//giving.cu.edu/fund/gynecologic-oncology-fellowship-fund

but the CMS also doesn't allow me to just input: /fund/gynecologic-oncology-fellowship-fund

<img width="874" alt="Screen Shot 2021-10-29 at 11 45 26 AM" src="https://user-images.githubusercontent.com/91230278/139479839-670bb4c9-9f7a-4597-8e76-b297e4e19170.png">

**Comment by alexfinnarn** [comment]
Yep, this is related to an issue of keeping fund names/links synced between the CMS and other data sources. That's why providing the whole URL is done vs. looking up as an autocomplete field before.

I updated the code on staging and now they point to the right place, in my testing.
