### ISSUE TITLE
Financials page edits

### ISSUE THREAD

**Issue by tskillern** [CUCentralAdvancement/essential-cu#472]
- [x] (1) The title/headline for the page needs something in between "transformative" and "fueling" -- either a dash, or it needs to be two clauses like "Philanthropy is transformative. It fuels passion, motivation and joy."

- [x] (2) Endowment graph: Let's say "Tens of thousands of donors" instead of "Thousands" to match our 54K number this last fy.

- [x] (3) $371.2 million graph: Either add "an" before assessment or make assessment plural

- [x] (4) Gifts section: 

- [ ] 
- [x] - The correct gift number is 54,543.
- [x] - Let's not use the word "donation." Because you just used "gift," maybe "contribution" or "investment."
- [x] - Let's say, "When you invest in CU, your impact is might" instead of what's there. The "thousands" is imprecise and we should focus on the "you."
- [x] - Gift size is $6,806.

- [x] (5) Donor section:

- [x] - The correct donor number is 29,793.
- [x] - This is lower priority, but the part that says "XX,XXX donors like you helped CU create change..." had me confused on first read since the headline is split from the sentence that follow. 

- [x] (6) Endowments section: 

- [x] - Lowercase "value" under the graph. 
- [x] - This needs a period or colon after it: Here is the recent performance of the LTIP against the policy benchmark
- [x] - The endowment graph for 15 year should be 8.7% for the LTIP.

- [x] (7) Transfers section:

- [x] - This should have a period: That’s how much the CU Foundation transferred to CU last fiscal year

- [x] (8) The "Download Our Financials" headline looks like a link, but it's not.

**Comment by Feissit** [comment]
@alexfinnarn Can you take care of these changes?

- [ ] Change Value to lowercase: value
![Screen Shot 2021-11-02 at 10 55 57 AM](https://user-images.githubusercontent.com/91230278/139910581-fb472d04-90c3-4ac9-85ff-a56130ed8170.png)

- [ ] The value above the bronze bar in 15 year should represent 8.7% instead of 7.4%
![Screen Shot 2021-11-02 at 10 56 48 AM](https://user-images.githubusercontent.com/91230278/139910755-8fa7c22f-4336-4232-ad26-908f3ef47c22.png)

- [ ] Turn the words "Download Our Financials" into a link to the full audited financials
![Screen Shot 2021-11-02 at 10 58 19 AM](https://user-images.githubusercontent.com/91230278/139910964-d58b2c80-2cb5-4515-9434-c26171678733.png)

**Comment by Feissit** [comment]
@tskillern -- I changed this to two sentences with periods to break it up, but I don't think it looks as nice/clean as

**Philanthropy is transformative**
Fueling passion, motivation and joy

It's not grammatically correct, but the bolded text reads pretty clear imo. Can we revert to the previous version? A dash might look odd here too

![Screen Shot 2021-11-02 at 2 02 20 PM](https://user-images.githubusercontent.com/91230278/139943891-e435bef6-6b33-4089-bef2-504dc1519b6c.png)

**Comment by alexfinnarn** [comment]
@tskillern @Feissit I updated those three items and pushed them to the staging environment.

**Comment by tskillern** [comment]
> @tskillern -- I changed this to two sentences with periods to break it up, but I don't think it looks as nice/clean as
> 
> **Philanthropy is transformative** Fueling passion, motivation and joy
> 
> It's not grammatically correct, but the bolded text reads pretty clear imo. Can we revert to the previous version? A dash might look odd here too
> 
> ![Screen Shot 2021-11-02 at 2 02 20 PM](https://user-images.githubusercontent.com/91230278/139943891-e435bef6-6b33-4089-bef2-504dc1519b6c.png)

@Feissit I replied to the github email and thought it'd get here, but I guess not. I'm fine with this: 

**Philanthropy is transformative**
Fueling passion, motivation and joy

But I think it was "fuels" not "fueling" which wouldn't make sense. Fueling is fine and with a hard return, like you have.

**Comment by tskillern** [comment]
All financials content edits are confirmed and good to go, unless @Feissit you want to revisit the main headline. I know there are existing display problems with the legends in the pie charts, but the content is ready. cc @alexfinnarn

**Comment by Feissit** [comment]
I created a pull request for the headline as discussed above, but maybe it hasn't merged yet?
