### ISSUE TITLE
UCCS story edits

### ISSUE THREAD

**Issue by tskillern** [CUCentralAdvancement/essential-cu#474]
- [x] (1) Subhead should not have commas around his name, or should be rephrased as "A first-generation college senior, Johnathan Gachuzo Gonzalez is lifting..."
- [ ] 
- [x] (2) The pull quote is confusing me for a few reasons: (1) it is not clear it's a quote because there are no quote marks; (2) it doesn't attribute it to him.
- [ ] 
- [x] (3) I know we have Cyrus as the photographer in the credits. If we only had his photos in the project, I'd be fine with not having photo credits anywhere. But the hand-out photos (the soccer one, etc.) would leave people to think that he took them. Can we add credits to the captions?
- [ ] 
- [x] (4) In the "My first day of high school" quote: Is there an errant hard return between "or" and "programs"?
**Fei -- I don't see one in the CMS**
- [ ] 
- [x] (5) In the Pre-Collegiate Program graph, use "earn" not "win" for scholarships.
- [ ] 
- [x] (6) In the "Giving expands student opportunities" module, let's say "Donors gave $53 million last fiscal year to merit and need-based scholarships for students like Gachuzo." (CU didn't actually "spend" that money -- and some of those gifts might not actually be used for years to come, depending on how they're given.)
- [ ] 
- [x] (7) Let's say "Learn more about our Financials" instead of "the" Financials.
- [ ] 
- [x] (8) The banana quote needs a comma after banana. The "math" part is also confusing. I'm not sure what that means. Maybe that second part of the quote isn't necessary?
- [ ] 
- [x] (9) The caption for Jony and his father doesn't seem like it needs "a recently finished house" -- just seems out of nowhere. Or if you keep, say that his father worked to build it? If that's true?
- [ ] 
- [x] (1) After that photo, you have three quotes in a row with three attributions. I can't remember if we solved for this in the latest drafts, but it feels off to have successive quotes all from the same person. I think you have a few options, but this seems the clearest: Paraphrase the start of the second quote with something like: "His dad works in construction, and Gachuzo sees him toiling on projects every day. "He used to take me to construction sites..." And then combine the last two quotes in one graph."

**Comment by Feissit** [comment]
This is updated. It will take a while for the changes to update on the live version.

**Comment by tskillern** [comment]
@Feissit looks good
