### ISSUE TITLE
AMC story edits

### ISSUE THREAD

**Issue by tskillern** [CUCentralAdvancement/essential-cu#477]
- [x] (1) In the "In 2018, Lampe retired..." graph: I agree somewhat with Marlee's take on this, though I wouldn't characterize it as "bleak." It does seem abrupt to go into the "According to the Ovarian Cancer Research Alliance" sentence from the previous. I think it's how you say "undiagnosed," so maybe a transition sentence like this? "In 2018, Lampe retired as the president of a software company. She was enthusiastically exploring new careers when she was hospitalized due to symptoms from ovarian **cancer, though she hadn't yet been diagnosed. The outcome for patients like Lampe are mixed:** According to the Ovarian Cancer Research Alliance, 60% of ovarian cancers are not diagnosed until patients have reached stage three of the disease, when five-year survival rates are around 39%. 

- [x] (2) Don't capitalize "Counseling and Career Development." We don't cap degree unless they use proper nouns like "English literature."

- [x] (3) Change "...**spends** months at a time" to "**spent** months at a time..." since she's no longer doing that.

- [x] #480

- [x] (5) The "little things" quote should say "Lampe said"

- [x] (6) Caption with notes should hyphenate "thank-you" in "Thank-you notes...." "Towards" should be "toward."

- [x] (7) Second graph under Carter photo: "toward" not "towards"

- [x] (8) Same graph: "patients' wishes" not "patient's wishes" since other words indicate plurality.

- [x] (9) In the "mid-September" graph: Maybe this makes it clearer? "In mid-September, she said that her “two to three weeks” had run out two weeks **before that**."

- [x] (10) Endowments module: Either put comma before "which" or make it "that."

- [x] (11) Change to "our" instead of "the" Financials.

**Comment by Feissit** [comment]
Changes made in CMS, takes time to refresh on live

**Comment by tskillern** [comment]
@Feissit all looks good
