### ISSUE TITLE
Denver story edits

### ISSUE THREAD

**Issue by tskillern** [CUCentralAdvancement/essential-cu#478]
- [x] (1) Subhead should not have commas around her name, unless you say "A speech pathologist..."
- [ ] 
- [x] (2) I agree that we should use his last name on first reference in the first sentence. I'm fine with first name elsewhere.
- [ ] 
- [x] (3) Maybe "People want things..." instead of "Others want things..." Others might not be clear on first read that you mean people.
- [ ] 
- [x] (4) This story has spaces around the dashes in some places, though other stories don't.
- [ ] 
- [x] (5) Add "old" after "26 months."
- [ ] 
- [x] (6) The caption under the yoga ball photo is not a complete sentence, but it had a period. This is inconsistent from other captions in other stories.
- [ ] 
- [x] (7) In the Financials module, change "fundraisers" to "donors." And change "the" to "our".
- [ ] 
- [x] (8) In Bodine quote, add comma before "which" -- "Many of our families have small incomes which they need to cover basics..."
- [ ] 
- [x] (9) Graham's restaurant photo caption is not a sentence but has a period.
- [ ] 
- [x] (10) I think it's "drive-thru" not "drive-through"

**Comment by Feissit** [comment]
Changes applied to CMS, it will take some time to be reflected on the live version

**Comment by tskillern** [comment]
@Feissit not seeing the changes to this story on staging.

**Comment by Feissit** [comment]
That's weird, I am seeing the changes here: https://essential-staging-cu.herokuapp.com/impact-reports/joy/stories-preview/joy-of-independence

**Comment by tskillern** [comment]
Strange. They're there now. 

- [ ] One fix: Fast-food should be hyphenated in the caption, per MW

**Comment by Feissit** [comment]
Done. Also added a closing parenthesis to the last photo caption. Takes a while to catch up to staging.
