### ISSUE TITLE
Update graphic and link on CUF page

### ISSUE THREAD

**Issue by duquennoisa** [CUCentralAdvancement/essential-cu#481]
Please update the graphic and link here https://giving.cu.edu/about-us/university-colorado-foundation

Graphic is here: https://www.dropbox.com/s/qk64lzyd4zrf6ry/IR21-CUFsite.png?dl=0

Update on 11/08

**Acceptance Criteria**

- [x] Updated graphic and link on site.

**Comment by alexfinnarn** [comment]
@duquennoisa the block is used in a few places across the site. I set it up on the test server and will make these changes in production on Monday.

- https://giving-test.cu.edu/about-us/university-colorado-foundation
- https://giving-test.cu.edu/about-us/central-cu-advancement
- https://giving-test.cu.edu/about-us/cu-foundation/cu-foundation-financial-and-investment-documents

**Comment by alexfinnarn** [comment]
@duquennoisa This is now live on the production site. Let me know if there's anything else left to do.
