### ISSUE TITLE
- The link "largest gifts to date" doesn't match the same style as the others.

### ISSUE THREAD

**Issue by Feissit** [CUCentralAdvancement/essential-cu#482]
Can you apply the turquoise link styling to this link (largest gift to date) as well? @duquennoisa it's not in the mock, but perhaps it'd be best to keep link styling consistent within body text?

![Screen Shot 2021-11-02 at 1 51 04 PM](https://user-images.githubusercontent.com/91230278/139942396-292791d0-b641-480b-88bb-7014f045074b.png)

**Comment by alexfinnarn** [comment]
The link style has been updated and pushed to the staging environment.
