### ISSUE TITLE
Change story card image div background color  and add new art. 

### ISSUE THREAD

**Issue by duquennoisa** [CUCentralAdvancement/essential-cu#491]
Please change the background color on the story card image div to    
background-color: #fffaeb;

Change should be on the homepage as well as on the end of story cards. 

This will work better with the new art 
![image](https://user-images.githubusercontent.com/70037329/140549155-595b74a5-9917-41af-8fcd-4c25db89a02e.png)

**Comment by alexfinnarn** [comment]
@duquennoisa I updated the background color, but until images are transparent it won't show up. Let me know any issues with this going forward.

**Comment by duquennoisa** [comment]
@alexfinnarn looks good in the staging environment !
