### ISSUE TITLE
Financials page legend error

### ISSUE THREAD

**Issue by Feissit** [CUCentralAdvancement/essential-cu#498]
Global public equities is listed in the legend twice (I can't change this in the pencil icon) -- The 4% in grey on the legend should say "Fixed income and cash"

This is a minor error, but high priority to fix ASAP

![image001 27  copy](https://user-images.githubusercontent.com/91230278/142236698-6cc80fe0-23f0-4299-9ebb-77551a64e397.jpg)

**Comment by alexfinnarn** [comment]
@Feissit I updated the legend on https://essential-staging-cu.herokuapp.com/impact-reports/joy/financials. If that looks good to you, I can push this to the production instance.

**Comment by Feissit** [comment]
@alexfinnarn Looks good please push!

**Comment by alexfinnarn** [comment]
Cool. Pushed to production.
