### ISSUE TITLE
Convert Footer Component To What Is Used In Giving Frontend App

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/essential-cu#53]
The only difference is white on black instead of black on white.

https://github.com/CUCentralAdvancement/giving-frontend/blob/master/components/global/Footer.js

**Comment by kmackvolt** [comment]
I'm assuming I will handle the styling once the footer is populated with the HTML content.

**Comment by alexfinnarn** [comment]
There may be some miscommunication here. I don't want to confuse Kelly or fall outside of the communication protocol so I will "at" @duquennoisa and @tskillern .

I see "populated by Alex from CMS" for the footer links on https://projects.invisionapp.com/freehand/document/k07PZQPB6. However, I hard-coded the first block with the button and then put the remaining menu links in https://github.com/CUCentralAdvancement/giving-frontend/blob/master/data/menus.js for the three "menu blocks".

I was going to just dump the same code into this project and switch the background and text colors; however, the tools I was  using to style things are different. Kelly can take the hardcoded links in the `Footer.js` component linked above and the links from the `menus.js` I linked in this comment to do as he pleases.

Otherwise, I can try and use the styling he's added already, but my intention was to match giving.cu.edu which doesn't have a rounded button...so I'm guessing the footer is specific to this site/project and not a 1:1 with current footers.

If Kelly is supposed to style the footer in the included SOW, then I would have him take the links listed there and write the HTML how he wants it. He can import the menu link data just like the stories are imported, and to be clear, the CMS doesn't have menu information in it at this point. It only has story data.

**Comment by duquennoisa** [comment]
If we can have the background be white, I don't care so much about the button. 
Does that work?

**Comment by alexfinnarn** [comment]
Sure.

**Comment by tskillern** [comment]
@alexfinnarn @duquennoisa Just double-checking here: do any of these conversations or changes regarding the footer affect Kelly?

**Comment by alexfinnarn** [comment]
No. Styling will be localized to the Footer component...at least I can't think of anything that would affect Kelly's work.

**Comment by tskillern** [comment]
ok

**Comment by alexfinnarn** [comment]
@duquennoisa and @tskillern Are the links the same as in the https://giving.cu.edu/ footer?

**Comment by duquennoisa** [comment]
> @duquennoisa and @tskillern Are the links the same as in the https://giving.cu.edu/ footer?

@alexfinnarn Yes
