### ISSUE TITLE
Add Font Awesome Support?

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/essential-cu#55]
I've added it in the giving-frontend app: https://github.com/CUCentralAdvancement/giving-frontend/pull/64/files

However, we never really discussed using it on this project or I forgot about that. I know there were custom icons used in past design files.

This issue can be used to track if and how Font Awesome is used on the project as I'm not sure of the licensing limitations.

**Comment by kmackvolt** [comment]
Currently we don't need Font Awesome support.
