### ISSUE TITLE
Need direction on page Title tags

### ISSUE THREAD

**Issue by kmackvolt** [CUCentralAdvancement/essential-cu#57]
Sometime I need to know what the HTML <title> tags should be for the various pages.

Currently the home page is "Onward" and Story pages are "Title", for example.

"Impact Report 2020 | University of Colorado" or something like that would be appropriate. The story title property from the CMS can be used in the page title as well.

**Comment by tskillern** [comment]
Home page -- "University of Colorado 2020 Donor Impact Report"

Story page -- please use the story title derived through CMS

Financials page --  "University of Colorado Fiscal Year 2020 Philanthropy Financials"
