### ISSUE TITLE
Need arrows used on mobile Story Cards (all colors)

### ISSUE THREAD

**Issue by kmackvolt** [CUCentralAdvancement/essential-cu#59]
Since we are not using Font Awesome I need graphics provided for all colors of arrows provided on the mobile story cards. I think that would be 4 colors - the base, and then 3 for the different Interest tag colors.

![arrows-needed](https://user-images.githubusercontent.com/40502718/93526125-d43d1f80-f8eb-11ea-8c52-4cebc877fc41.PNG)

**Comment by duquennoisa** [comment]
@kmackvolt here is a folder with PNGs (1x and 2x the size). https://www.dropbox.com/sh/1zl4zfqnxfy94t1/AADhrhU_KuPgbp4ugK5OcZkka?dl=0

My understanding is we are not doing mobile highlighting because it wasn't in the SOW.
