### ISSUE TITLE
Add utm values to social sharing query strings

### ISSUE THREAD

**Issue by kreynen** [CUCentralAdvancement/essential-cu#62]
https://developers.facebook.com/docs/sharing/reference/feed-dialog
https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/parameter-reference1

utm_campaign: 2020ImpactReport 
utm_source: IR20_Share 
utm_medium: Social
utm_content: [campus]_[interest] or [campus] (based on current story)

LinkedIn no longer works like Twitter and Facebook. It looks like in July of 2020, LinkedIn changed from using `https://www.linkedin.com/shareArticle?mini=true&url=http://developer.linkedin.com&title=LinkedIn%20Developer%20Network&summary=My%20favorite%20developer%20program&source=LinkedIn` to using the `https://www.linkedin.com/sharing/share-offsite/?url= http://leeds.ly/FacesOfLeeds` that gets a few additional values from the target URL's metadata. 

share-offsite still allows utm values in the query parameters as long as they are URL encoded.

https://www.linkedin.com/post-inspector/ shows how the page metadata will be used, but if you use a redirect like http://leeds.ly/FacesOfLeeds or essential.cu.edu in the url, LinkedIn uses the data and url at the end of any redirect chain.

![_17__LinkedIn](https://user-images.githubusercontent.com/385234/93777504-1b742a80-fbe2-11ea-8d2a-1d4665497d1e.png)

**Comment by kreynen** [comment]
Just noting that current version of https://github.com/CUCentralAdvancement/essential-cu/blob/master/pages/impact-reports/onward/index.js#L19 does not include the required utm values. In the CU 2020 - Tracker google spreadsheet, CU-43 and CU-41 are marked as `dev complete`. I don't have access to the details in Jira to know if this was an intentional change or it was missed when the functionality was review, but unless these values are added this reporting isn't going to work the way we discussed.

**Comment by tskillern** [comment]
@kmackvolt Adding UTM values to URL from social sharing buttons is something Kevin brought up today. We would like to track clicks from those buttons. Without the UTM values, we can't tell the difference b/t the buttons and someone copying the URL from the browser and sharing. 

**This would be the lowest priority of remaining fixes.** 

from Kevin: 

> it really is just adding the query string to the URL in the code that's already there. I just didn't want to make this a priority since we're not really expecting too much traffic from the share buttons

**Comment by kmackvolt** [comment]
The requirements doc mentions this as far as social sharing needs:
"_Top social module
Description: The social module gives the user the ability to share the story content to a social channel. The social channels are Facebook, Twitter and LinkedIn._ "
and this:
"_There are additional requirements (like tracking, backend, CMS and other technical considerations) that this document does not address._ "

**Please detail what additional requirements you have.**

Such as:
Are you talking about the open graph tags on every page and/or the social media share buttons only on story pages?

Do you need me to capture the querystring on site entry, and pass that on to be used throughout the site? 

What about return visitors, should that be cookied?
etc.

Depending on what exactly you want done, it is not necessarily a trivial amount of work even though it's low priority. I did not estimate for anything beyond what I've done so far with the opengraph tags on every page and the social sharing buttons on the story page.

@pspaeth

**Comment by mattroush** [comment]
@kmackvolt Minimum requirements here would be that the links generated for sharing widgets would have the following query string attached to the URL of current page they are sharing:

`?utm_campaign=2020ImpactReport&utm_source=IR20_Share&utm_medium=Social`

To make it easy, this same query string would apply to all social share links regardless of platform. If you can urlencode them so it works for linkedin, even better.

They do not need to be dynamic, and they do not need to be cookied when user arrives from one of these links. This is simply to help us get a rough estimation of traffic from these social share widgets in google analytics.

Does that help?

cc @pspaeth @tskillern @kreynen

**Comment by kmackvolt** [comment]
PR for this:
https://github.com/CUCentralAdvancement/essential-cu/pull/117

Note that all sharing URLs are hard coded to **https://essential.cu.edu/**.. so code would need to be deployed there to actually test.

**Comment by mattroush** [comment]
@alexfinnarn this should be completed and can be closed. to validate, just go to prod site, click one of the share buttons on a page and confirm that query string [in this comment above](https://github.com/CUCentralAdvancement/essential-cu/issues/62#issuecomment-710055285) is attached to page url.

**Comment by alexfinnarn** [comment]
confirmed
