### ISSUE TITLE
Changes to links in footer

### ISSUE THREAD

**Issue by tskillern** [CUCentralAdvancement/essential-cu#78]
@alexfinnarn Anne's footer content does not reflect recent changes made to the global giving site footer. I don't know if these are changes you should/can make, or if I should assign to Kelly. 

1. Under Quicklinks: Remove "Beta Access" link -- not sure why that's in there. 

2. Under Quicklinks: Under "Guide to Giving" please add "Give by Mail/Check" and link to https://giving.cu.edu/make-gift-mail

![Screen Shot 2020-09-29 at 9 55 45 AM](https://user-images.githubusercontent.com/70039323/94582912-10e90f00-023a-11eb-8dd3-0b5597638b3f.png)

3. Under Give Now button: Change address to this: 1800 Grant Street, Suite 725

4. Under Give Now button: Can you remove the pipe here and put CU Foundation on a new line? 

![image (7)](https://user-images.githubusercontent.com/70039323/94582704-c9628300-0239-11eb-9db7-9f16b2361532.png)

**Comment by kmackvolt** [comment]
@tskillern It looks like the links are coming from a data file in the codebase. I will make these updates.

**Comment by tskillern** [comment]
thanks @kmackvolt
