### ISSUE TITLE
Features/financials follow-up fixes

### ISSUE THREAD

**Issue by tskillern** [CUCentralAdvancement/essential-cu#89]
@kmackvolt 

cc @pspaeth 

Re: https://github.com/CUCentralAdvancement/essential-cu/pull/84 which I merged earlier.

Here are fixes we'll eventually need to home page and financials. There are several, but all fairly small. 

**HOME PAGE**

**1. Financials module on home page**

a) All the elements in this module (headlines, body text, image) should go to the financials URL (same as the button).

![financials home page clickables](https://user-images.githubusercontent.com/70039323/95119285-f8309b80-0708-11eb-86c1-4af7e1d1412f.png)

b) When linking these elements, please do not use underlining or color change on hover. 

**2. Mission module**

a) Please swap the URLs for these two parts of this module. The left one (CU Foundation) should to go to: https://giving.cu.edu/about-us/university-colorado-foundation and the right one (CU Advancement) should go to: https://giving.cu.edu/about-us/central-cu-advancement

b) Remove blue color on hover in this module.

**3. Stories link in global header**

a) The stories button in the global header does not go to #stories anchor link on the home page. I didn't note this in issue related to header because the home page hadn't been built yet. But it's not anchoring above the story-card module in this iteration. 

**FINANCIALS PAGE**
 
**1. Remove excess padding on mobile in this spot**

![move excess padding on mobile](https://user-images.githubusercontent.com/70039323/95119697-9b81b080-0709-11eb-8f9c-2a9563d0a879.png)

**2. All charts should be 723 x 586 proportions**

See: https://www.dropbox.com/s/b2ajphk33e91vdf/all%20charts%20should%20be%20723%20x%20586.png?dl=0

**3. This is also a chart in the first section and should be 723 x 586 proportions:**

![make 723 x 586](https://user-images.githubusercontent.com/70039323/95119861-e3083c80-0709-11eb-81fe-7811f3768808.png)

**4. The padding in between the headline and the image should be the same as below the image:** 

![make top padding the same as the bottom](https://user-images.githubusercontent.com/70039323/95119969-121eae00-070a-11eb-96e4-d6b20ba2b370.png)

**5. Move this headline above the image; keep consistent padding as above:**

![move headline 1](https://user-images.githubusercontent.com/70039323/95120009-1d71d980-070a-11eb-84e2-ba1f11cc6b07.png)

**6. Here are some text updates to financials page:** 

a) In the page intro, please change to this text that's highlighted: 

![Screen Shot 2020-10-05 at 1 39 15 PM](https://user-images.githubusercontent.com/70039323/95124152-3d0c0080-0710-11eb-9a48-fb8a54488ba7.png)

b) In the third section down, please add the word "as" here: 

![Screen Shot 2020-10-05 at 1 25 02 PM](https://user-images.githubusercontent.com/70039323/95122800-42684b80-070e-11eb-8d74-0418ba54b290.png)

c) In the intro paragraph of the second part, please remove the word "that" and put in "for" here: 

![Screen Shot 2020-10-05 at 1 16 01 PM](https://user-images.githubusercontent.com/70039323/95122862-5d3ac000-070e-11eb-8194-806d33747d21.png)

d) In the first section of the second part, please insert these updates: 

![Screen Shot 2020-10-05 at 1 18 14 PM copy](https://user-images.githubusercontent.com/70039323/95123201-d1756380-070e-11eb-8754-1bda377c0abf.png)

e) The paragraph text in this section is incorrect. It should be this: "Here is the LTIP's annualized investment performance compared to our policy benchmark."

![Screen Shot 2020-10-05 at 1 31 06 PM](https://user-images.githubusercontent.com/70039323/95123380-1ac5b300-070f-11eb-81db-2fd23c4d5aad.png)

Kelly -- the URL for the very bottom is coming soon.

**Comment by kmackvolt** [comment]
@tskillern The **Home** page was not intended to be reviewed yet per the feature/financials PR, but I went ahead and made all of these changes and added the Stories anchor link. Vertical padding around the stories and financials modules on the home page has not been finalized, as I am still working on mocking up the financial module reorder based on cookie. Other than that, the home page can be reviewed now.

**Financials page**. The dimensions of all images were taken from inspecting the placeholders in Invision. The exact sizes don't matter, as they are all responsively/fluidly sized; thus, I did not change the sizes of any placeholder images on the page in this branch.

All other copy/padding changes are done.

**Comment by tskillern** [comment]
@kmackvolt thanks for taking care of those and understood. Sorry if I missed that it wasn't ready for review. 

Re: incorrect sizes of charts: Anne mentioned to me after I created the issue that she might've missed a step going from sketch to invision and that caused the issue.
